title: stats
name: Richard Chandler
#logo: /assets/img/logo.png
description: Exercises in model fitting for my graduate students
#google_analytics:
theme: jekyll-theme-minimal
header_pages:
  - README.md
  - ./exercises/lm/lm.md