title: stats
author: Richard Chandler
email: rchandler@warnell.uga.edu
description: Exercises in model fitting for my graduate students
theme: minima
header_pages:
  - exercises/exercises.md
  - keys/keys.md
  